# Generated by Django 3.2.8 on 2021-10-16 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=255, verbose_name='Tool Name')),
                ('tool_link', models.URLField(verbose_name='Tool Link')),
                ('tool_description', models.TextField(verbose_name='Tool Description')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=255, verbose_name='Tag')),
                ('Fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tools.tools')),
            ],
        ),
    ]
